movie.titles <- c(#### MARVEL TITLES
  "The Amazing Spider-Man 2",
  "Ant-Man",
  "Marvel's The Avengers","Avengers: Age of Ultron",
  "Blade","Blade II","Blade: Trinity",
  "Captain America: The First Avenger",
  "Daredevil",
  "Deadpool",
  'Big Hero 6',
  "Elektra",
  "Fantastic Four(2005)","Fantastic Four(2015)","Fantastic Four: Rise of the Silver Surfer",
  "Ghost Rider","Ghost Rider: Spirit of Vengeance",
  "Howard The Duck", 
  "Hulk","The Incredible Hulk",
  "Iron Man","Iron Man 2","Iron Man 3",
  "Captain America: The Winter Soldier",
  "Guardians of the Galaxy",
  "Captain America: Civil War",
  "The Punisher","Punisher: War Zone",
  "Spider-Man","Spider-Man 2","Spider-Man 3","The Amazing Spider-Man",
  "Thor","Thor: The Dark World",
  "X-Men Origins: Wolverine","The Wolverine",
  "X-Men:Apocalypse","X2: X-Men United", "X-Men: The Last Stand",
  "X-Men","X-Men: Days of Future Past","X-Men: First Class",
  
  #### DC TITLES
  "Batman","The Dark Knight Rises","Batman Begins","Batman Forever",
  "Batman: Mask of the Phantasm","Batman Returns","Batman Robin", 
  "Catwoman",
  "Constantine",
  "The Dark Knight",
  "Suicide Squad",
  "Green Lantern",
  "Jonah Hex",
  "The Losers",
  "Red 2","Red",
  "Steel",
  "Supergirl",
  "Superman","Superman Returns", "Superman II","Man of Steel","Batman v Superman: Dawn of Justice",
  "Superman III","Superman IV: The Quest for Peace", 
  "V for Vendetta", "Watchmen",
  
  #### OTHERS TITLES
  
  "2 Guns","300","300: Rise of an Empire","30 Days of Night",
  "American Splendor","Alien vs Predator","Alien vs Predator Requiem",
  "Black Mask","Buffy the Vampire Slayer",
  "Bulletproof Monk","Bullet to the Head",
  "Casper","Chronicle (2012)",
  "Cowboys & Aliens",
  "The Crow",
  "The Crow:City of Angels",
  "Darkman",
  "The Diary of a Teenage Girl", "Dick Tracy",
  "Dredd",
  "From Hell",
  "Ghost world",
  "The Green Hornet",
  "Hancock",
  "Hellboy",
  "Hellboy II: The Golden Army",
  "Hercules",
  "A history of violence",
  "I, Frankenstein",
  "The Incredibles",
  "Iron Monkey",
  "Josie and the Pussycats",
  "Judge Dredd",
  "Kick-Ass",
  "Kick-Ass 2",
  "The League of Extraordinary Gentlemen",
  "The Mask",
  "The Mask of Zorro",
  "Megamind",
  "Men in Black",
  "Men in Black II",
  "Men in Black III",
  "Monkeybone",
  "Mystery Men",
  "Oblivion",
  "The Phantom",
  "The Powerpuff Girls Movie",
  "Mighty Morphin' Power Rangers",
  "Priest",
  "Richie Rich",    
  "RIPD",
  "Road to Perdition",
  "The Rocketeer",
  "Scott Pilgrim vs the World",
  "Kingsman: The Secret Service",
  "The Shadow",
  "Sin City",
  "Sin City: A Dame to Kill For",
  "Sky High",
  "Snowpiercer","Spawn","The Spirit",
  "Super",
  "My Super Ex-Girlfriend",
  "Superhero Movie",
  "Surrogates",
  "Tank Girl ",
  "Teenage Mutant Ninja Turtles",
  "Timecop",
  "The Adventures of Tintin",
  "Teenage Mutant Ninja Turtles (2014)",
  "Teenage Mutant Ninja Turtles: Out of the Shadow",
  "Teenage Mutant Ninja Turtles III","TMNT",
  "Teenage Mutant Ninja Turtles II: The Secret of the Ooze",
  "Virus",
  "Wanted",
  "Whiteout",
  "The X-Files: I Want to Believe",
  "Zoom",
  "The Legend of Zorro")