
revision <- list(
  "Fantastic Four(2005)" = c("Scientist Reed Richards (Loan Gruffudd) persuades his arrogant former classmate Victor von Doom (Julian McMahon), to fund his experiments with cosmic energy. On von Doom's space station, the crew - including astronaut Ben Grimm (Michael Chiklis), researcher Sue Storm (Jessica Alba) and pilot Johnny Storm (Chris Evans) - are exposed to a mysterious cosmic storm that bestows super powers upon them. As they cope with their transfortmations, von Doom vows his revenge."),
  "Fantastic Four: Rise of the Silver Surfer" = c("Reed (Ioan Gruffudd), Susan (Jessica Alba), Johnny (Chris Evans) and Ben (Michael Chiklis) face an intergalactic messenger who has arrived to prepare Earth for its destruction. While the enigmatic being wreaks havoc around the world, the heroic quartet must also contend with the unexpected return of their enemy, Victor Von Doom."),
  "Thor: The Dark World" = c("In ancient times, the gods of Asgard fought and won a war against an evil race known as the Dark Elves. The survivors were neutralized, and their ultimate weapon -- the Aether -- was buried in a secret location. Hundreds of years later, Jane Foster (Natalie Portman) finds the Aether and becomes its host, forcing Thor (Chris Hemsworth) to bring her to Asgard before Dark Elf Malekith (Christopher Eccleston) captures her and uses the weapon to destroy the Nine Realms -- including Earth."),
  "X-Men: Days of Future Past" = c("Convinced that mutants pose a threat to humanity, Dr. Bolivar Trask (Peter Dinklage) develops the Sentinels, enormous robotic weapons that can detect a mutant gene and zero in on that person. In the 21st century, the Sentinels have evolved into highly efficient killing machines. With mutants now facing extinction, Wolverine (Hugh Jackman) volunteers to go back in time and rally the X-Men of the past to help change a pivotal moment in history and thereby save their future."),
  "Dredd" = c("Mega City One is a vast, violent metropolis where felons rule the streets. The only law lies with cops called 'judges', who act as judge, jury and executioner, and Dredd (Karl Urban) is one of the city's most feared. One day, Dredd is partnered with Cassandra (Olivia Thirlby), a rookie with powerful psychic abilities. A report of a terrible crime sends Dredd and Cassandra to a dangerous area controlled by Ma-Ma (Lena Headey), a drug lord who will stop at nothing to protect her empire."),
  "Teenage Mutant Ninja Turtles: Out of the Shadows" = c("The turtles face a new challenge when Shredder escapes from custody and joins forces with Baxter Stockman, a mad scientist who plans to use a serum to take over the world. Along for the ride are Bebop and Rocksteady, two dimwitted henchmen who provide plenty of muscle. Luckily, the turtles have their own allies in April O'Neil, Vernon Fenwick and Casey Jones, a hockey-masked vigilante. As the pizza-loving heroes prepare for battle, the notorious Krang also emerges to pose an even greater threat."),
  "Kick-Ass 2" = c("Dave (Aaron Taylor-Johnson), aka Kick-Ass, and Mindy (Chloë Grace Moretz), aka Hit Girl, are trying to live as normal teenagers and briefly form a crime-fighting team. After Mindy is busted and forced to retire as Hit Girl, Dave joins a group of amateur superheroes led by Col. Stars and Stripes (Jim Carrey), a reformed mobster. Just as Dave and company start to make a real difference on the streets, the villain formerly known as Red Mist (Christopher Mintz-Plasse) rears his head yet again."),
  "Blade: Trinity" = c("The war between humans and vampires continues, but the humans' best hope, human-vampire hybrid warrior Blade (Wesley Snipes), has been framed for countless murders, turning popular sentiment against him. The vampire leader responsible for Blade's bad publicity is Danica Talos (Parker Posey), who's determined to finally lead her bloodthirsty compatriots to victory. Now Blade must team up with a band of rogue vampire hunters (Ryan Reynolds, Jessica Biel) to save humanity."),
  "Spider-Man"= c("'Spider-Man' centers on student Peter Parker (Tobey Maguire) who, after being bitten by a genetically-altered spider, gains superhuman strength and the spider-like ability to cling to any surface. He vows to use his abilities to fight crime, coming to understand the words of his beloved Uncle Ben: 'With great power comes great responsibility'."),
  "Batman Forever" = c("Batman (Val Kilmer) faces off against two foes: the schizophrenic, horribly scarred former District Attorney Harvey Dent, aka Two-Face (Tommy Lee Jones), and the Riddler (Jim Carrey), a disgruntled ex-Wayne Enterprises inventor seeking revenge against his former employer by unleashing his brain-sucking weapon on Gotham City's residents. As the caped crusader also deals with tortured memories of his parents' murder, he has a new romance, with psychologist Chase Meridian (Nicole Kidman)."),
  "The Mask" = c("When timid bank clerk Stanley Ipkiss (Jim Carrey) discovers a magical mask containing the spirit of the Norse god Loki, his entire life changes. While wearing the mask, Ipkiss becomes a supernatural playboy exuding charm and confidence which allows him to catch the eye of local nightclub singer Tina Carlyle (Cameron Diaz). Unfortunately, under the mask's influence, Ipkiss also robs a bank, which angers junior crime lord Dorian Tyrell (Peter Greene), whose goons get blamed for the heist."),
  "RIPD" = c("Veteran lawman Roy Pulsifer (Jeff Bridges) works for the R.I.P.D., a legendary police force charged with finding monstrous spirits who are disguised as ordinary people but are trying to avoid their final judgment by hiding out among the living. When Roy and his new partner, Nick Walker (Ryan Reynolds), uncover a plot that could end all life, they must discover a way to restore the cosmic balance or else watch the tunnel to the afterlife start sending angry souls back to the world of the living.")
)